import type { JobRegionFilter } from './jobRecommendations';

export interface JobRegionOption extends JobRegionFilter {
  shortLabel: string;
  provinceCode: string;
}

export interface JobRegionProvince extends JobRegionOption {
  children: JobRegionOption[];
}

type ChildDefinition = readonly [code: string, label: string];

function province(code: string, label: string, children: readonly ChildDefinition[]): JobRegionProvince {
  return {
    code,
    label,
    shortLabel: label,
    provinceCode: code,
    children: children.map(([childCode, childLabel]) => ({
      code: `${code}/${childCode}`,
      label: `${label} ${childLabel}`,
      shortLabel: childLabel,
      provinceCode: code,
    })),
  };
}

export const JOB_REGION_ANY: JobRegionOption = {
  code: 'any',
  label: '지역 무관',
  shortLabel: '지역 무관',
  provinceCode: 'any',
};

export const JOB_REGION_PROVINCES: readonly JobRegionProvince[] = [
  province('seoul', '서울특별시', [
    ['jongno-gu', '종로구'],
    ['jung-gu', '중구'],
    ['yongsan-gu', '용산구'],
    ['seongdong-gu', '성동구'],
    ['gwangjin-gu', '광진구'],
    ['dongdaemun-gu', '동대문구'],
    ['jungnang-gu', '중랑구'],
    ['seongbuk-gu', '성북구'],
    ['gangbuk-gu', '강북구'],
    ['dobong-gu', '도봉구'],
    ['nowon-gu', '노원구'],
    ['eunpyeong-gu', '은평구'],
    ['seodaemun-gu', '서대문구'],
    ['mapo-gu', '마포구'],
    ['yangcheon-gu', '양천구'],
    ['gangseo-gu', '강서구'],
    ['guro-gu', '구로구'],
    ['geumcheon-gu', '금천구'],
    ['yeongdeungpo-gu', '영등포구'],
    ['dongjak-gu', '동작구'],
    ['gwanak-gu', '관악구'],
    ['seocho-gu', '서초구'],
    ['gangnam-gu', '강남구'],
    ['songpa-gu', '송파구'],
    ['gangdong-gu', '강동구'],
  ]),
  province('busan', '부산광역시', [
    ['jung-gu', '중구'],
    ['seo-gu', '서구'],
    ['dong-gu', '동구'],
    ['yeongdo-gu', '영도구'],
    ['busanjin-gu', '부산진구'],
    ['dongnae-gu', '동래구'],
    ['nam-gu', '남구'],
    ['buk-gu', '북구'],
    ['haeundae-gu', '해운대구'],
    ['saha-gu', '사하구'],
    ['geumjeong-gu', '금정구'],
    ['gangseo-gu', '강서구'],
    ['yeonje-gu', '연제구'],
    ['suyeong-gu', '수영구'],
    ['sasang-gu', '사상구'],
    ['gijang-gun', '기장군'],
  ]),
  province('daegu', '대구광역시', [
    ['jung-gu', '중구'],
    ['dong-gu', '동구'],
    ['seo-gu', '서구'],
    ['nam-gu', '남구'],
    ['buk-gu', '북구'],
    ['suseong-gu', '수성구'],
    ['dalseo-gu', '달서구'],
    ['dalseong-gun', '달성군'],
    ['gunwi-gun', '군위군'],
  ]),
  province('incheon', '인천광역시', [
    ['jung-gu', '중구'],
    ['dong-gu', '동구'],
    ['michuhol-gu', '미추홀구'],
    ['yeonsu-gu', '연수구'],
    ['namdong-gu', '남동구'],
    ['bupyeong-gu', '부평구'],
    ['gyeyang-gu', '계양구'],
    ['seo-gu', '서구'],
    ['ganghwa-gun', '강화군'],
    ['ongjin-gun', '옹진군'],
  ]),
  province('gwangju', '광주광역시', [
    ['dong-gu', '동구'],
    ['seo-gu', '서구'],
    ['nam-gu', '남구'],
    ['buk-gu', '북구'],
    ['gwangsan-gu', '광산구'],
  ]),
  province('daejeon', '대전광역시', [
    ['dong-gu', '동구'],
    ['jung-gu', '중구'],
    ['seo-gu', '서구'],
    ['yuseong-gu', '유성구'],
    ['daedeok-gu', '대덕구'],
  ]),
  province('ulsan', '울산광역시', [
    ['jung-gu', '중구'],
    ['nam-gu', '남구'],
    ['dong-gu', '동구'],
    ['buk-gu', '북구'],
    ['ulju-gun', '울주군'],
  ]),
  province('sejong', '세종특별자치시', []),
  province('gyeonggi', '경기도', [
    ['suwon-si', '수원시'],
    ['seongnam-si', '성남시'],
    ['uijeongbu-si', '의정부시'],
    ['anyang-si', '안양시'],
    ['bucheon-si', '부천시'],
    ['gwangmyeong-si', '광명시'],
    ['pyeongtaek-si', '평택시'],
    ['dongducheon-si', '동두천시'],
    ['ansan-si', '안산시'],
    ['goyang-si', '고양시'],
    ['gwacheon-si', '과천시'],
    ['guri-si', '구리시'],
    ['namyangju-si', '남양주시'],
    ['osan-si', '오산시'],
    ['siheung-si', '시흥시'],
    ['gunpo-si', '군포시'],
    ['uiwang-si', '의왕시'],
    ['hanam-si', '하남시'],
    ['yongin-si', '용인시'],
    ['paju-si', '파주시'],
    ['icheon-si', '이천시'],
    ['anseong-si', '안성시'],
    ['gimpo-si', '김포시'],
    ['hwaseong-si', '화성시'],
    ['gwangju-si', '광주시'],
    ['yangju-si', '양주시'],
    ['pocheon-si', '포천시'],
    ['yeoju-si', '여주시'],
    ['yeoncheon-gun', '연천군'],
    ['gapyeong-gun', '가평군'],
    ['yangpyeong-gun', '양평군'],
  ]),
  province('gangwon', '강원특별자치도', [
    ['chuncheon-si', '춘천시'],
    ['wonju-si', '원주시'],
    ['gangneung-si', '강릉시'],
    ['donghae-si', '동해시'],
    ['taebaek-si', '태백시'],
    ['sokcho-si', '속초시'],
    ['samcheok-si', '삼척시'],
    ['hongcheon-gun', '홍천군'],
    ['hoengseong-gun', '횡성군'],
    ['yeongwol-gun', '영월군'],
    ['pyeongchang-gun', '평창군'],
    ['jeongseon-gun', '정선군'],
    ['cheorwon-gun', '철원군'],
    ['hwacheon-gun', '화천군'],
    ['yanggu-gun', '양구군'],
    ['inje-gun', '인제군'],
    ['goseong-gun', '고성군'],
    ['yangyang-gun', '양양군'],
  ]),
  province('chungbuk', '충청북도', [
    ['cheongju-si', '청주시'],
    ['chungju-si', '충주시'],
    ['jecheon-si', '제천시'],
    ['boeun-gun', '보은군'],
    ['okcheon-gun', '옥천군'],
    ['yeongdong-gun', '영동군'],
    ['jeungpyeong-gun', '증평군'],
    ['jincheon-gun', '진천군'],
    ['goesan-gun', '괴산군'],
    ['eumseong-gun', '음성군'],
    ['danyang-gun', '단양군'],
  ]),
  province('chungnam', '충청남도', [
    ['cheonan-si', '천안시'],
    ['gongju-si', '공주시'],
    ['boryeong-si', '보령시'],
    ['asan-si', '아산시'],
    ['seosan-si', '서산시'],
    ['nonsan-si', '논산시'],
    ['gyeryong-si', '계룡시'],
    ['dangjin-si', '당진시'],
    ['geumsan-gun', '금산군'],
    ['buyeo-gun', '부여군'],
    ['seocheon-gun', '서천군'],
    ['cheongyang-gun', '청양군'],
    ['hongseong-gun', '홍성군'],
    ['yesan-gun', '예산군'],
    ['taean-gun', '태안군'],
  ]),
  province('jeonbuk', '전북특별자치도', [
    ['jeonju-si', '전주시'],
    ['gunsan-si', '군산시'],
    ['iksan-si', '익산시'],
    ['jeongeup-si', '정읍시'],
    ['namwon-si', '남원시'],
    ['gimje-si', '김제시'],
    ['wanju-gun', '완주군'],
    ['jinan-gun', '진안군'],
    ['muju-gun', '무주군'],
    ['jangsu-gun', '장수군'],
    ['imsil-gun', '임실군'],
    ['sunchang-gun', '순창군'],
    ['gochang-gun', '고창군'],
    ['buan-gun', '부안군'],
  ]),
  province('jeonnam', '전라남도', [
    ['mokpo-si', '목포시'],
    ['yeosu-si', '여수시'],
    ['suncheon-si', '순천시'],
    ['naju-si', '나주시'],
    ['gwangyang-si', '광양시'],
    ['damyang-gun', '담양군'],
    ['gokseong-gun', '곡성군'],
    ['gurye-gun', '구례군'],
    ['goheung-gun', '고흥군'],
    ['boseong-gun', '보성군'],
    ['hwasun-gun', '화순군'],
    ['jangheung-gun', '장흥군'],
    ['gangjin-gun', '강진군'],
    ['haenam-gun', '해남군'],
    ['yeongam-gun', '영암군'],
    ['muan-gun', '무안군'],
    ['hampyeong-gun', '함평군'],
    ['yeonggwang-gun', '영광군'],
    ['jangseong-gun', '장성군'],
    ['wando-gun', '완도군'],
    ['jindo-gun', '진도군'],
    ['sinan-gun', '신안군'],
  ]),
  province('gyeongbuk', '경상북도', [
    ['pohang-si', '포항시'],
    ['gyeongju-si', '경주시'],
    ['gimcheon-si', '김천시'],
    ['andong-si', '안동시'],
    ['gumi-si', '구미시'],
    ['yeongju-si', '영주시'],
    ['yeongcheon-si', '영천시'],
    ['sangju-si', '상주시'],
    ['mungyeong-si', '문경시'],
    ['gyeongsan-si', '경산시'],
    ['uiseong-gun', '의성군'],
    ['cheongsong-gun', '청송군'],
    ['yeongyang-gun', '영양군'],
    ['yeongdeok-gun', '영덕군'],
    ['cheongdo-gun', '청도군'],
    ['goryeong-gun', '고령군'],
    ['seongju-gun', '성주군'],
    ['chilgok-gun', '칠곡군'],
    ['yecheon-gun', '예천군'],
    ['bonghwa-gun', '봉화군'],
    ['uljin-gun', '울진군'],
    ['ulleung-gun', '울릉군'],
  ]),
  province('gyeongnam', '경상남도', [
    ['changwon-si', '창원시'],
    ['jinju-si', '진주시'],
    ['tongyeong-si', '통영시'],
    ['sacheon-si', '사천시'],
    ['gimhae-si', '김해시'],
    ['miryang-si', '밀양시'],
    ['geoje-si', '거제시'],
    ['yangsan-si', '양산시'],
    ['uiryeong-gun', '의령군'],
    ['haman-gun', '함안군'],
    ['changnyeong-gun', '창녕군'],
    ['goseong-gun', '고성군'],
    ['namhae-gun', '남해군'],
    ['hadong-gun', '하동군'],
    ['sancheong-gun', '산청군'],
    ['hamyang-gun', '함양군'],
    ['geochang-gun', '거창군'],
    ['hapcheon-gun', '합천군'],
  ]),
  province('jeju', '제주특별자치도', [
    ['jeju-si', '제주시'],
    ['seogwipo-si', '서귀포시'],
  ]),
] as const;

export const JOB_REGION_CHILD_COUNT = JOB_REGION_PROVINCES.reduce((total, item) => total + item.children.length, 0);

export function findJobRegionOption(code: string): JobRegionOption | undefined {
  if (code === JOB_REGION_ANY.code) return JOB_REGION_ANY;
  for (const item of JOB_REGION_PROVINCES) {
    if (item.code === code) return item;
    const child = item.children.find(candidate => candidate.code === code);
    if (child) return child;
  }
  return undefined;
}
